// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1
// source: copyfrom.go

package queries

import (
	"context"
)

// iteratorForCreateEmployees implements pgx.CopyFromSource.
type iteratorForCreateEmployees struct {
	rows                 []CreateEmployeesParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateEmployees) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateEmployees) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].Email,
		r.rows[0].UserName,
		r.rows[0].TenantID,
		r.rows[0].DepartmentID,
	}, nil
}

func (r iteratorForCreateEmployees) Err() error {
	return nil
}

func (q *Queries) CreateEmployees(ctx context.Context, arg []CreateEmployeesParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"employees"}, []string{"email", "user_name", "tenant_id", "department_id"}, &iteratorForCreateEmployees{rows: arg})
}

// iteratorForCreateTenants implements pgx.CopyFromSource.
type iteratorForCreateTenants struct {
	rows                 []CreateTenantsParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateTenants) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateTenants) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].Name,
		r.rows[0].Status,
		r.rows[0].Code,
	}, nil
}

func (r iteratorForCreateTenants) Err() error {
	return nil
}

func (q *Queries) CreateTenants(ctx context.Context, arg []CreateTenantsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"tenants"}, []string{"name", "status", "code"}, &iteratorForCreateTenants{rows: arg})
}
