// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package queries

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Department struct {
	ID       int16       `json:"id"`
	Name     string      `json:"name"`
	Code     string      `json:"code"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

type Employee struct {
	ID           pgtype.UUID `json:"id"`
	Email        string      `json:"email"`
	UserName     string      `json:"user_name"`
	TenantID     pgtype.UUID `json:"tenant_id"`
	ManagerID    pgtype.UUID `json:"manager_id"`
	DepartmentID pgtype.Int2 `json:"department_id"`
}

type Tenant struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Status    bool               `json:"status"`
	Code      pgtype.Text        `json:"code"`
	Size      pgtype.Int4        `json:"size"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
