// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateDepartment(ctx context.Context, arg CreateDepartmentParams) (Department, error)
	CreateEmployee(ctx context.Context, arg CreateEmployeeParams) (Employee, error)
	CreateEmployees(ctx context.Context, arg []CreateEmployeesParams) (int64, error)
	CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error)
	CreateTenants(ctx context.Context, arg []CreateTenantsParams) (int64, error)
	GetCountEmployeeWithGivenDeptCodeInTenant(ctx context.Context, arg GetCountEmployeeWithGivenDeptCodeInTenantParams) (int64, error)
	GetDepartmentID(ctx context.Context) ([]int16, error)
	GetEmployeeWithGivenDeptCodeInTenant(ctx context.Context, arg GetEmployeeWithGivenDeptCodeInTenantParams) ([]GetEmployeeWithGivenDeptCodeInTenantRow, error)
	GetTenantIDFromName(ctx context.Context, name string) (pgtype.UUID, error)
	GetTentantID(ctx context.Context) ([]pgtype.UUID, error)
	UpdateEmployeFromEmail(ctx context.Context, arg UpdateEmployeFromEmailParams) (Employee, error)
}

var _ Querier = (*Queries)(nil)
